### ISSUE TITLE
An issue template for bug report needed

### ISSUE THREAD

**Issue by AJV009** [devcpune/Awesome-DevC-Contributors#19]
As of now we only have two templates!
So if in-case someone new to making contribution finds an issue he or she should be able to make a proper bug report!
Task: Creation of a third template for fixing bugs.
+ additional: Creation of a third template for reporting errors.

**Comment by AJV009** [comment]
@shriaas2898  what do you thing about it, should we do it?

**Comment by shriaas2898** [comment]
People can open another issue but yes keeping a template for bug is a good idea!

**Comment by rutujadhanawade** [comment]
I want to work on this issue.

**Comment by AJV009** [comment]
Yes @rutujadhanawade  go on!
We are expecting a small good issue template for bug reports.
