### ISSUE TITLE
The github-actions bot automatically closes all issues without check!

### ISSUE THREAD

**Issue by AJV009** [devcpune/Awesome-DevC-Contributors#20]
The github-actions bot which is made to just automatically add/update contributions just closes other blank issues despite the fact that its not a template or a add/update issue!
Task: Fix the github-actions bot behavior (for closing issues)

**Comment by AJV009** [comment]
See this is the problem!
as you can see the github bot just closed this issue!

**Comment by shriaas2898** [comment]
Fixed with commit 2697be1
