### ISSUE TITLE
Bug - characters like "|" or "-" are skipped by the program which causes an error.

### ISSUE THREAD

**Issue by kkkkkabir** [devcpune/Awesome-DevC-Contributors#30]
So here is what happened when I tried to submit my PR to this repo:-

I followed the template as it is, but when I made the PR, the bot would state that my link is invalid and I should try again. This was odd as all my links were valid and working. So what was the problem?
Here is one line which was the issue:

`**Name:** Removed link "Google Reskilling India Program | Pluralsight" | **Link**: https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1281`

In the String "Google Reskilling India Program | Pluralsight", there is a "**|**" character that is causing the issue. I even tried using a "**-**" but it didn't work. I don't know what exactly is the problem but it is a bug. I removed the **"|"** character and my issue was successfully submitted.

**For the time being, it is better if you just state the name of the PR without using any characters like "|, -" etc.**

Thanks to @AJV009 for pointing this out and helping me in my issue!

**Comment by shriaas2898** [comment]
Hey @kkkkkabir we have updtaed our mechanisim to add contributions and this bug is now resolved!

**Comment by kkkkkabir** [comment]
Great!!

**Comment by AJV009** [comment]
Hey @shriaas2898  does the update also have the OSIP PR validation?
Like filtering PRs made during OSIP!
