### ISSUE TITLE
add|rutujadhanawade

### ISSUE THREAD

**Issue by rutujadhanawade** [devcpune/Awesome-DevC-Contributors#41]
https://github.com/fbdevelopercircles/FbDevcCommunityContent/pull/147
https://github.com/devcpune/devcpune.github.io/pull/1
https://github.com/facebook/codemod/pull/117
https://github.com/Shubham230198/The-Uplift-Project-DSA/pull/42

**Comment by rutujadhanawade** [comment]
@shriaas2898 will you please help me with this?
actually I trying to add my contributions but the GitHub run is failing again and again. Will you please tell me whats wrong with my issue?

**Comment by shriaas2898** [comment]
Hey, @rutujadhanawade there was some problem with the workflow but now it is fixed! Can you check the above link though? When I try to access it, it says not found. Maybe there is some typo in the link address, please rectify it and edit the issue!

**Comment by rutujadhanawade** [comment]
yeah now it is fine.
@shriaas2898 Thank you. :+1:

**Comment by rutujadhanawade** [comment]
Hii @shriaas2898 actually as per the rules of immersion program we have to successfully create 4 pull request.. It is not necessary that it should be merged. 
So my one PR is not merged yet so it is not visible in the readme https://github.com/facebook/codemod/pull/117 .
Will you please change that setting?

**Comment by rutujadhanawade** [comment]
Hii. @shriaas2898 will you please tell me why only 3 contributions are visible in readme, I have successfully created 4 PR s.
May be this is due to same PR name. Can you please look into this matter?

**Comment by shriaas2898** [comment]
Hey @rutujadhanawade Thanks for pointing out. Actually 2 of your PRs have same title which is creating conflict but don't worry it will be resolved in some time.

**Comment by rutujadhanawade** [comment]
Yeah. I just renamed my one PR..

**Comment by shriaas2898** [comment]
Awesome!
