### ISSUE TITLE
add|BhuvaneshHingal

### ISSUE THREAD

**Issue by BhuvaneshHingal** [devcpune/Awesome-DevC-Contributors#48]
https://github.com/praveenscience/PHP-eCertificate-Generator/pull/7
https://github.com/praveenscience/LinkedIn-Clone/pull/2
https://github.com/praveenscience/Portfolio-Tips-Tricks/pull/2
https://github.com/EddieJaoudeCommunity/hacktoberfest-practice/pull/91
https://github.com/EddieJaoudeCommunity/hacktoberfest-practice/pull/97
https://github.com/EddieJaoudeCommunity/hacktoberfest-practice/pull/116
https://github.com/firstcontributions/first-contributions/pull/30205
https://github.com/sudhanshu456/full-stack-devs-techera/pull/2
https://github.com/amannirala13/College-Assignments/pull/2
https://github.com/zero-to-mastery/start-here-guidelines/pull/7733
https://github.com/ming-tsai/ming-tsai/pull/9
https://github.com/EddieJaoudeCommunity/gh-action-community/pull/38
https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/83
https://github.com/Meghna-DAS/Meghna-DAS/pull/2
https://github.com/vivmost/vivmost/pull/2
https://github.com/coding-blocks/make-a-pr/pull/737
https://github.com/devcpune/solid-doodle/pull/44

**Comment by BhuvaneshHingal** [comment]
@shriaas2898 Can you please help me with this? Why is it not getting added? 🤔

**Comment by shriaas2898** [comment]
Hey this repo is to showcase the PRs made only during the Open Source Immersion Programme, please remove the ones which are not made during that period.
